### ISSUE TITLE
Link to versioned images

### ISSUE THREAD

**Issue by robinbb** [tweag/stack-docker-nix#1]
Please link to *versioned* images of builds of this Dockerfile (on quay.io, or Docker Hub, perhaps).

**Comment by mboes** [comment]
What do you mean by versioned? Do you mean with tags for each version? We currently have only one tag defined on DockerHub: "latest". DockerHub doesn't support automatically defining new tags for each new build. If you'd prefer that then we'll need to move to quay.io or similar. That said, with DockerHub we are free to define new tags on on as-need basis, say to retain a particular build forever in the future.

**Comment by mboes** [comment]
Actually, even quay.io doesn't support auto adding new tags for each build, AFAICT. We could potentially generate the images using Wercker, which does automatically add a new tag for each build. But at the cost of abandoning Dockerfiles (they [consider them harmful](http://blog.wercker.com/dockerfiles-considered-harmful)).
