### ISSUE TITLE
docker build fails, error getting status of '/nix/sources.nix'

### ISSUE THREAD

**Issue by aleeusgr** [tweag/stack-docker-nix#10]
**Describe the bug**
My task is to dokerize a Haskell web API. I added code from this repo and now on`docker build -t project-name .` I get: 
>Error: getting status of '/nix/sources.nix': No such file or directory

**To Reproduce**
1. $stack new project-name [template](https://github.com/commercialhaskell/stack-templates/blob/master/spock.hsfiles)
2. add [nix support](https://github.com/tweag/haskell-stack-nix-example)
3. test in nix-shell, program runs fine.
4. code from here -> Dockerfile
5. $docker build -t project-name .
6. Observe error.

**Expected behavior**
Build finishes with no errors, docker run can be tested with `curl -v localhost:8080`

**Environment**
 - OS name + version: Linux nixos 5.15.70 #1-NixOS
 - Version of the code: ??

What may be wrong?
Thank you!

**Comment by thufschmitt** [comment]
There's a documentation mismatch, indeed. The docker build need to have access to all your Nix files, which in the case of the example repo you use don't just include `shell.nix` but also the `nix` directory. So instead of `ADD shell.nix /`, your `Dockerfile` probably needs something like `ADD shell.nix nix /`

**Comment by aleeusgr** [comment]
Thank you for quick response! Testing

```
FROM tweag/stack-docker-nix                                                                                 [0/413]
  1 
  2 ADD shell.nix nix /
  3 #ADD shell.nix /
  4 # Clean up non-essential downloaded archives after provisioning a shell.
  5 RUN nix-shell /shell.nix --indirect --add-root /nix-shell-gc-root \
  6     && nix-collect-garbage
  7 RUN IN_NIX_SHELL=1 nix-instantiate \
  8     --add-root /shell.drv --indirect /shell.nix \
  9     && nix-collect-garbage
```
>10:56 $ docker build -t hello-spock .
Sending build context to Docker daemon  98.52MB
Step 1/4 : FROM tweag/stack-docker-nix
 ---> 9d2dab805e1d
Step 2/4 : ADD shell.nix nix /
 ---> cd2df2e94c94
Step 3/4 : RUN nix-shell /shell.nix --indirect --add-root /nix-shell-gc-root     && nix-collect-garbage
 ---> Running in 29c2187f3054
error: getting status of '/nix/sources.nix': No such file or directory
The command '/bin/sh -c nix-shell /shell.nix --indirect --add-root /nix-shell-gc-root     && nix-collect-garbage' returned a non-zero code: 1

**Comment by aleeusgr** [comment]
```
FROM tweag/stack-docker-nix                                                                                   [0/0]
  1 
  2 ADD shell.nix /
  3 ADD nix /nix
  4 #ADD nix/sources.json /
  5 #ADD nix/sources.nix /
  6 #ADD nix/stack-integration.nix /
  7 # Clean up non-essential downloaded archives after provisioning a shell.
  8 RUN nix-shell /shell.nix --indirect --add-root /nix-shell-gc-root \
  9     && nix-collect-garbage
 10 RUN IN_NIX_SHELL=1 nix-instantiate \
 11     --add-root /shell.drv --indirect /shell.nix \
 12     && nix-collect-garbage
```
`docker build -t name .`

>Step 4/5 : RUN nix-shell /shell.nix --indirect --add-root /nix-shell-gc-root     && nix-collect-garbage
 ---> Running in 7710f5fa8cbd
unpacking 'https://github.com/NixOS/nixpkgs/archive/abfd31179174133ab8131139d650297bf4da63b7.tar.gz'...
error: evaluation aborted with the following error message: '
This version of Nixpkgs requires Nix >= 2.2, please upgrade:

hmm, 
`$nix-channel --list`
>nixos https://nixos.org/channels/nixos-22.05

nix version: nix (Nix) 2.8.1

**Comment by thufschmitt** [comment]
> This version of Nixpkgs requires Nix >= 2.2, please upgrade:

Oh my, that's old 😱 

I'm not sure how I can force a rebuild of the image on docker hub. You should be able to do that locally though (`docker build`-ing this repo) to get a more recent one in the meantime. That should upgrade the Nix version that it uses

**Comment by aleeusgr** [comment]
"Rebuild docker image locally" sounds like what I am trying to do;
`docker build` returns `error: upgrade nix`

Am I understanding something wrong?

**Comment by aleeusgr** [comment]
But I understand "upgrade nix version".
Hm, I should maybe replace 
FROM 
with a nixOS image?

Testing...

**Comment by thufschmitt** [comment]
Sorry, I meant rebuild the `tweag/stack-docker-nix` image. So clone this repo, and run `docker build -t tweag/stack-docker-nix .` in it.

But that actually won't work because the `nixos/nix` image (that it's based on) has changed too much in the meantime. I'm not sure how we can fix this except by rewriting the `Dockerfile` of thie repo from scratch 😒

**Comment by aleeusgr** [comment]
Thank you!
Testing...
`git clone git@github.com:tweag/stack-docker-nix.git && cd stack-docker-nix`
`docker build -t tweag/stack-docker-nix .`
>13:09 $ docker build -t tweag/stack-docker-nix .
Sending build context to Docker daemon   76.8kB
Step 1/13 : FROM nixos/nix
 ---> 467492ebb5e2
Step 2/13 : MAINTAINER Mathieu Boespflug <m@tweag.io>
 ---> Using cache
 ---> 107a747abd93
Step 3/13 : RUN echo http://dl-cdn.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories
 ---> Running in 36dbf74c125b 
/bin/sh: line 1: /etc/apk/repositories: No such file or directory
The command '/bin/sh -c echo http://dl-cdn.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories' returned a non-zero code: 1

**Comment by aleeusgr** [comment]
hm, I add 
`RUN mkdir -p /etc/apk`
to Dockerfile and now
>bin/sh: line 1: apk: command not found

**Comment by aleeusgr** [comment]
```
#Dockerfile
RUN mkdir -p /etc/apk 
RUN echo http://dl-cdn.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories
```
 ---> Running in 3d17bd9ad304
/bin/sh: line 1: /etc/apk/repositories: No such file or directory
```
#Dockerfile
FROM alpine
RUN mkdir -p /etc/apk 
RUN echo http://dl-cdn.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories
```

ERROR: unable to select packages:
  python (no such package):
    required by: world[python]
The command '/bin/sh -c apk --update add ca-certificates python shadow' returned a non-zero code: 1

**Comment by aleeusgr** [comment]
Hm, maybe its simpler for me to build my own Dockerfile? 
testing..

**Comment by aleeusgr** [comment]
https://mpickering.github.io/posts/2018-09-19-nix-artefacts.html
