### ISSUE TITLE
Remove Python dependency

### ISSUE THREAD

**Issue by robinbb** [tweag/stack-docker-nix#3]
It would be nice if the image were smaller. For me, the image (as measured using 'docker images') has size 547 MB. Maybe some Python dependencies can be removed by rewriting entrypoint.py in shell script?

**Comment by mboes** [comment]
I'd love to get rid of the Python dependency. But see earlier conversation
about this. It's surprisingly hard to write a correct entrypoint in
shellscript that preserves whitespaces in arguments. Feel free to propose
one. Just keep in mind that it needs to work given things like:

```
$ stack docker run stack --docker-internal 'SomeConstr Nothing (Just "someString")' arg1 ... argN
```
